# Generated by Django 5.2.9 on 2025-12-30 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('speciality', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Busy', 'Busy'), ('On Vacation', 'On Vacation')], default='Available', max_length=20)),
            ],
        ),
    ]
