# Generated by Django 5.2.9 on 2025-12-31 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_appointment_doctor_alter_appointment_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='busy_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
