# Generated by Django 5.2.9 on 2025-12-31 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_consultationrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultationrequest',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
