# Generated by Django 5.2.9 on 2025-12-31 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_alter_consultationrequest_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultationrequest',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('in_progress', 'In Progress'), ('contacted', 'Contacted'), ('done', 'Done')], default='new', max_length=20),
        ),
    ]
