# Generated by Django 5.1.3 on 2026-05-28 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0009_contactmessage_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="doctor",
            name="busy_until",
        ),
        migrations.RemoveField(
            model_name="doctor",
            name="status",
        ),
    ]
